/**
 * NodeEconomy — Resource node-based economy system for .io arena.
 *
 * Replaces worker-based gathering with:
 * - Resource nodes on the map (mineral/gas deposits)
 * - Extractor buildings placed on nodes generate passive income
 * - Destroying enemy extractors cuts their income
 * - Kill bounties reward the attacker
 *
 * No workers needed — economy is strategic (where to expand, when to defend).
 */

import type { PlayerResources } from '../types';

// ─── Constants ───────────────────────────────────────────────────────────

/** Minerals per second generated by one extractor on a mineral node */
export const EXTRACTOR_MINERAL_RATE = 1.5;

/** Gas per second generated by one extractor on a gas node */
export const EXTRACTOR_GAS_RATE = 0.75;

/** Starting minerals for new player */
export const ARENA_STARTING_MINERALS = 200;

/** Starting gas for new player */
export const ARENA_STARTING_GAS = 0;

/** Starting supply cap */
export const ARENA_STARTING_SUPPLY = 15;

/** Kill bounty: minerals awarded per supply point of destroyed unit */
export const KILL_BOUNTY_PER_SUPPLY = 10;

/** Building destruction bounty: % of building mineral cost awarded */
export const BUILDING_DESTROY_BOUNTY_PCT = 0.25;

// ─── Resource Node Tracking ──────────────────────────────────────────────

export interface ResourceNode {
  id: number;            // Unique node ID
  col: number;           // Tile column
  row: number;           // Tile row
  type: 'mineral' | 'gas';
  ownerFaction: number;  // 0 = unclaimed
  extractorEid: number;  // Entity ID of extractor building (0 = none)
}

/**
 * NodeEconomyState — tracks all resource nodes and income.
 */
export class NodeEconomyState {
  nodes: ResourceNode[] = [];
  private nextNodeId = 1;

  /** Register a resource node on the map. */
  addNode(col: number, row: number, type: 'mineral' | 'gas'): ResourceNode {
    const node: ResourceNode = {
      id: this.nextNodeId++,
      col, row, type,
      ownerFaction: 0,
      extractorEid: 0,
    };
    this.nodes.push(node);
    return node;
  }

  /** Claim a node for a faction (when extractor is built). */
  claimNode(nodeId: number, factionId: number, extractorEid: number): void {
    const node = this.nodes.find(n => n.id === nodeId);
    if (node) {
      node.ownerFaction = factionId;
      node.extractorEid = extractorEid;
    }
  }

  /** Release a node (when extractor is destroyed). */
  releaseNode(nodeId: number): void {
    const node = this.nodes.find(n => n.id === nodeId);
    if (node) {
      node.ownerFaction = 0;
      node.extractorEid = 0;
    }
  }

  /** Find a node at a tile position. */
  findNodeAt(col: number, row: number): ResourceNode | undefined {
    return this.nodes.find(n => n.col === col && n.row === row);
  }

  /** Count nodes owned by a faction. */
  countOwned(factionId: number): number {
    return this.nodes.filter(n => n.ownerFaction === factionId).length;
  }

  /** Get all nodes owned by a faction. */
  getOwnedNodes(factionId: number): ResourceNode[] {
    return this.nodes.filter(n => n.ownerFaction === factionId);
  }

  /**
   * Tick income — add passive resources from owned extractors.
   * Called once per server tick.
   */
  tickIncome(dt: number, resources: Record<number, PlayerResources>): void {
    for (const node of this.nodes) {
      if (node.ownerFaction === 0 || node.extractorEid === 0) continue;
      const res = resources[node.ownerFaction];
      if (!res) continue;

      if (node.type === 'mineral') {
        res.minerals += EXTRACTOR_MINERAL_RATE * dt;
      } else {
        res.gas += EXTRACTOR_GAS_RATE * dt;
      }
    }
  }
}

/**
 * Award kill bounty to the attacker's faction.
 * Called when a unit or building dies.
 */
export function awardKillBounty(
  attackerFaction: number,
  victimSupply: number,
  resources: Record<number, PlayerResources>,
): void {
  const res = resources[attackerFaction];
  if (!res) return;
  res.minerals += Math.round(victimSupply * KILL_BOUNTY_PER_SUPPLY);
}

/**
 * Award building destruction bounty.
 */
export function awardBuildingBounty(
  attackerFaction: number,
  buildingMineralCost: number,
  resources: Record<number, PlayerResources>,
): void {
  const res = resources[attackerFaction];
  if (!res) return;
  res.minerals += Math.round(buildingMineralCost * BUILDING_DESTROY_BOUNTY_PCT);
}
